name: flutter_tex_js_example
description: Demonstrates how to use the flutter_tex_js plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tex_js:
    path: ../

  flutter_tex: ^3.6.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
