name: flutter_tex_js_example
description: Demonstrates how to use the flutter_tex_js plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tex_js:
    path: ../

  flutter_tex: ^3.6.7+5
  catex: ^0.0.1+2
  libv_markdown: ^1.0.1
  # flutter_math is not compatible with Flutter SDK 1.18+
  # flutter_math: ^0.1.3
  # fluttex does not support iOS
  # fluttex: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
