name: flutter_tex_js
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: com.madlonkay.flutter_tex_js
        pluginClass: FlutterTexJsPlugin
      ios:
        pluginClass: FlutterTexJsPlugin
