name: flutter_tex_js
description: A lightweight TeX plugin that uses KaTeX (JavaScript) in a native web view to render to PNG
version: 1.2.17
homepage: https://github.com/amake/flutter_tex_js

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tex_js_android:
    # path: ../flutter_tex_js_android
    git:
      url: https://github.com/GoodOnuii-M/flutter_tex_js
      path: flutter_tex_js_android
  flutter_tex_js_ios:
    # path: ../flutter_tex_js_ios
    git:
      url: https://github.com/GoodOnuii-M/flutter_tex_js
      path: flutter_tex_js_ios
  flutter_tex_js_macos:
    # path: ../flutter_tex_js_macos
    git:
      url: https://github.com/GoodOnuii-M/flutter_tex_js
      path: flutter_tex_js_macos

  flutter_tex_js_platform_interface:
    # path: ../flutter_tex_js_platform_interface
    git:
      url: https://github.com/GoodOnuii-M/flutter_tex_js
      path: flutter_tex_js_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_tex_js_android
      ios:
        default_package: flutter_tex_js_ios
      macos:
        default_package: flutter_tex_js_macos
